# Generated by Django 3.2 on 2021-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels'),
        ),
    ]
